# Generated by Django 3.2.9 on 2023-05-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(help_text='amount in usdt')),
                ('status', models.CharField(choices=[('FAILURE', 'Failure'), ('IN_PROGRESS', 'In Progress'), ('PAYED', 'Payed'), ('PAYED_AND_CONFIRMED', 'Payed And Confirmed'), ('ADMIN_CHECK', 'Admin Check'), ('SUCCESS', 'Success')], default='IN_PROGRESS', max_length=64)),
                ('to_address', models.TextField()),
                ('trx_hash', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='chat_state',
            field=models.CharField(choices=[('GET_TRX_HASH', 'Get Trx Hash')], default=None, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.TextField()),
                ('active_days', models.PositiveBigIntegerField(default=90)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_links', to='users.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_links', to='users.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.user'),
        ),
    ]
