# Generated by Django 3.2.9 on 2023-05-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230521_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_state',
            field=models.CharField(choices=[('GET_TRX_HASH', 'Get Trx Hash'), ('NONE', 'None')], default='NONE', max_length=64, null=True),
        ),
    ]
