# Generated by Django 3.2.9 on 2023-05-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_chat_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'Failure'), ('IN_PROGRESS', 'In Progress'), ('PAYED', 'Payed'), ('PAYED_AND_CONFIRMED', 'Payed And Confirmed'), ('SUCCESS', 'Success')], default='IN_PROGRESS', max_length=64),
        ),
    ]
