# Generated by Django 3.2.9 on 2023-05-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='vpn',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='VPN',
        ),
    ]
