# Generated by Django 3.2.9 on 2023-05-27 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0007_auto_20230527_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddifyPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('panel_id', models.TextField()),
                ('admin_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_days', models.PositiveBigIntegerField(default=90)),
                ('usage_limit', models.PositiveBigIntegerField(default=50, help_text='In GB')),
                ('mode', models.CharField(choices=[('no_reset', 'No Reset'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='no_reset', max_length=20)),
                ('amount', models.PositiveBigIntegerField(default=7)),
                ('hiddify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.hiddifypanel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.TextField()),
                ('user_uuid', models.TextField()),
                ('active_days', models.PositiveBigIntegerField(default=90)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpns', to='payment.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpns', to='vpn.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpns', to='users.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('limit_per_user', models.IntegerField(default=-1)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.subscription')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
